const BOARD={


    BOARD_LOADING_REQUEST : "BOARD_LOADING_REQUEST",
    BOARD_LOADING_FAILURE : "BOARD_LOADING_FAILURE",
    BOARD_LOADING_SUCCESS : "BOARD_LOADING_SUCCESS",
   
   
    BOARD_UPLOADING_REQUEST : "BOARD_UPLOADING_REQUEST",
    BOARD_UPLOADING_FAILURE : "BOARD_UPLOADING_FAILURE",
    BOARD_UPLOADING_SUCCESS : "BOARD_UPLOADING_SUCCESS",
   
   
   BOARD_DETAIL_LOADING_REQUEST : "BOARD_DETAIL_LOADING_REQUEST",
   BOARD_DETAIL_LOADING_FAILURE : "BOARD_DETAIL_LOADING_FAILURE",
   BOARD_DETAIL_LOADING_SUCCESS : "BOARD_DETAIL_LOADING_SUCCESS",
   
   
   BOARD_EDIT_REQUEST : "BOARD_EDIT_REQUEST",
   BOARD_EDIT_FAILURE : "BOARD_EDIT_FAILURE",
   BOARD_EDIT_SUCCESS : "BOARD_EDIT_SUCCESS",
   
   BOARD_DELETE_REQUEST : "BOARD_DELETE_REQUEST",
   BOARD_DELETE_FAILURE : "BOARD_DELETE_FAILURE",
   BOARD_DELETE_SUCCESS : "BOARD_DELETE_SUCCESS",

   
   };
   export default BOARD;    
       
   
   
   
   
   
   
   